spring:
  redis:
    host: 101.200.40.98
    port: 6379
    password: xfsy2018
    database: 0
#    timeout: 60s  # 数据库连接超时时间，springboot2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
#    # 连接池配置，springboot2.0中直接使用jedis或者lettuce配置连接池
#    jedis:
#      pool:
#        # 最大空闲连接数
#        max-idle: 500
#        # 最小空闲连接数
#        min-idle: 50
#        # 等待可用连接的最大时间，负数为不限制
#        max-wait:  -1s
#        # 最大活跃连接数，负数为不限制
#        max-active: -1

#说明：Jedis和Lettuce的比较：
#
#　　　　　Jedis ：
#
#　　　　　　直连模式，在多个线程间共享一个 Jedis 实例时是线程不安全的，如果想要在多线程环境下使用 Jedis，需要使用连接池，
#
#　　　　　　每个线程都去拿自己的 Jedis 实例，当连接数量增多时，物理连接成本较高。
#
#　　　　　Lettuce：
#
#　　　　　　连接是基于Netty的，连接实例可以在多个线程间共享，
#
#　　　　　　所以，一个多线程的应用可以使用同一个连接实例，而不用担心并发线程的数量。当然这个也是可伸缩的设计，一个连接实例不够的情况也可以按需增加连接实例。
#
#　　　　　　通过异步的方式可以让我们更好的利用系统资源，而不用浪费线程等待网络或磁盘I/O。